2 lesson
dpolarov/f_js pull request #4
Opened 2020-05-18 13:18 UTC by dpolarov

array metod and function 
refactoring avia bilets, simplification

2020-05-18 20:27 UTC, arswarog requested changes

2020-05-18 20:27 UTC, arswarog commented on 2_lessons/2_parse_string/index.js
> +}
Считает корректно, но ответ возвращает не в том виде как указанно в задаче

2020-05-18 20:27 UTC, arswarog commented on 2_lessons/1_sum-object/index.js
> +  return result_object;
можно сразу return {count,sum};

2020-05-18 20:27 UTC, arswarog commented on 2_lessons/3_avia_tickets/fcs.js
> +}
Стоит выдавать ошибку если пассажир регистрируется повторно

2020-05-18 20:27 UTC, arswarog commented on 2_lessons/3_avia_tickets/fcs.js
> +  report.registration = ((nowTime > fl_record.registrationStarts) & nowTime < fl_record.registartionEnds);
&& вместо &
& - побитовая операция, используется для преобразование чисел
&& - логическая, используется для логических выражений

2020-05-18 21:45 UTC, dpolarov commented on 2_lessons/1_sum-object/index.js
> +  return result_object;
спасибо, исправил

2020-05-18 21:53 UTC, dpolarov commented on 2_lessons/3_avia_tickets/fcs.js
> +  report.registration = ((nowTime > fl_record.registrationStarts) & nowTime < fl_record.registartionEnds);
невнимательность ;(, спасибо

2020-05-18 21:58 UTC, dpolarov commented on 2_lessons/3_avia_tickets/fcs.js
> +}
наверно если билет уже активирован,
если пассажир пытается зарегистрироваться еще раз, это более общая ошибка.
Поставил проверку в конце.

2020-05-20 04:09 UTC, arswarog approved these changes

2020-05-20 04:09 UTC, arswarog commented on 2_lessons/2_parse_string/index.js
> +    return s;
можно записать это еще и так
```js
const word = itm;
const sum = itm.split('').reduce((a, current) => a + current.charCodeAt(0), 0);
return {word, sum};
```

2020-05-20 04:09 UTC, arswarog commented on 2_lessons/3_avia_tickets/fcs.js
> +  report.registration = ((nowTime > fl_record.registrationStarts) && nowTime < fl_record.registartionEnds);
скобочки, обрамляющие все выражение необязательны

2020-05-20 07:07 UTC, merged