4 lesson
dpolarov/f_js pull request #6
Opened 2020-05-27 10:15 UTC by dpolarov

2020-05-27 19:24 UTC, arswarog requested changes

2020-05-27 19:24 UTC, arswarog commented on 4_lessons/1_tree/tree.js
> +    position++;
скорее deep чем position.
или еще что-нибудь на подобии "глубина"

2020-05-27 19:24 UTC, arswarog commented on 4_lessons/1_tree/tree.js
> +}
Дубликат кода))

2020-05-27 19:24 UTC, arswarog commented on 4_lessons/1_tree/tree.js
> +    }
отступы поехали

2020-05-27 19:24 UTC, arswarog commented on 4_lessons/1_tree/tree.js
> +getChild3(document,0);
при объявлении функции можно указать значение по умолчанию
function getChild1(element, position = 0){
и тогда вызов будет понятнее
getChild1(document)

2020-05-27 19:24 UTC, arswarog commented on 4_lessons/1_tree/tree.js
> +function getChild1(element, position){
глядя на название функции, первая мысль что это получить какой-то дочерний элемент, видимо на позиции position в элементе element.
Надо давать понятные, говорящие имена.
Конкретно в данном случае число на конце имени абсолютно оправданно, но это очень частный случай

2020-05-28 09:52 UTC, dpolarov commented on 4_lessons/1_tree/tree.js
> +    position++;
nesting ?
Position имелось виду не глубина элемента ,а позиция вывода на экран

2020-05-28 09:53 UTC, dpolarov commented on 4_lessons/1_tree/tree.js
> +}
копи паст два раза , убрал

2020-05-28 09:53 UTC, dpolarov commented on 4_lessons/1_tree/tree.js
> +function getChild1(element, position){
getChildVarian3(element, nesting = 0)

2020-05-28 09:54 UTC, dpolarov commented on 4_lessons/1_tree/tree.js
> +getChild3(document,0);
Супер, не подумал ,,исправил

2020-05-28 17:49 UTC, arswarog approved these changes

2020-05-28 17:50 UTC, arswarog commented on 4_lessons/1_tree/tree.js
> +function getChild1(element, position){
printElementTree ?

2020-05-28 18:06 UTC, merged